### ISSUE TITLE
New support article on getting started with Python SDK

### ISSUE THREAD

**Issue by antonyharfield** [rfcx/rfcx-sdk-python#21]
Requirements
- Article in HelpScout
- Whenever a user/partner asks about downloading audio or integrating with our platform then we can send them the link to this article

**Comment by koonchaya** [comment]
I created the draft document [here](https://docs.google.com/document/d/1AABSE4Am9-gLG5oXA-INtO1DwVZSfHRdak67K_Xr9AE/edit?usp=sharing)
